name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_dotenv: ^5.1.0
  google_place: ^0.4.7
  google_geocoding:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
